### ISSUE TITLE
there are some errors in spiral_prac_2.ipynb

### ISSUE THREAD

**Issue by chaoshengt** [kaus98/spiral-graph-covid-nyc#1]
Dear @kaus98 , thank you for sharing your code. I found that there are some errors in spiral_prac_2.ipynb. 
```python
assert data_ind.shape[0] == data_usa.shape[0]

n = data_usa.Days_Passed.max()+1
```
'data_ind, data_usa' not defined.

Coulduld you fix your code file? Thank you! :)

**Comment by kaus98** [comment]
Hello @chaoshengt 
I have pushed new file main.ipynb which is working for all the graphs you can change the ISO codes for country and colors in notebook.
And it will work.

Thank You

**Comment by chaoshengt** [comment]
> 



> Hello @chaoshengt I have pushed new file main.ipynb which is working for all the graphs you can change the ISO codes for country and colors in notebook. And it will work.
> 
> Thank You

Thank you @kaus98 .  It works.  I will learn your code. Thank you so much.
